version: '3.7'
services:
  db:
    image: 'postgres:latest'
    container_name: 'database-container'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: restaurant-management

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  application:
    container_name: 'restaurant-container'
    image: 'restaurant-aplication:1.0'
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      PORT_POSTGRES: 5432
      USER_POSTGRES: postgres
      PASSWORD_POSTGRES: 123
